FROM node:20-bookworm-slim

WORKDIR /app

RUN apt-get update -y && apt-get install -y openssl postgresql-client && rm -rf /var/lib/apt/lists/*

COPY package*.json ./

RUN npm install

COPY . .

ENV DATABASE_URL="postgres://postgres:postgres@localhost:5432/postgres"

RUN npx prisma generate

EXPOSE 3000

CMD ["npm", "run", "dev"]
